# Makefile for programs from Lab 7 1617-CSS19
# Author: Niall Madden (Niall.Madden@NUIGalway.ie)
# Date: 13/03/2017

all : MakeGraphs MakeGraphsV02

MakeGraphs : MakeGraphs.cpp Vector09.cpp Vector09.h Matrix09.cpp Matrix09.h
	g++ -Wall MakeGraphs.cpp \
	Vector09.cpp Matrix09.cpp -o MakeGraphs

MakeGraphsV02 : MakeGraphsV02.cpp Vector09.cpp Vector09.h Matrix09V02.cpp Matrix09.h
	g++ -Wall MakeGraphsV02.cpp \
	Vector09.cpp Matrix09V02.cpp -o MakeGraphsV02
