#This Makefile for is for comiling 03Jacobi.cpp from
#  Week 7 of 1617-CS319. See
# http://www.maths.nuigalway.ie/~niall/CS319/Week07/
# Niall Madden (NUI Galway) Niall.Madden@NUIGalway.ie
# To use it, make sure the files listed below are in the
# same directory as this file, and run "make."

03Jacobi: 03Jacobi.cpp Matrix.cpp Vector.cpp  Matrix.h Vector.h
	g++ -Wall 03Jacobi.cpp Matrix.cpp  Vector.cpp -o 03Jacobi -lm


