#This Makefile for is for comiling 03Jacobi.cpp from
#  Week 7 of 1617-CS319. See
# http://www.maths.nuigalway.ie/~niall/CS319/Week07/
# Niall Madden (NUI Galway) Niall.Madden@NUIGalway.ie
# To use it, make sure the files listed below are in the
# same directory as this file, and run "make."

RunJacobi: RunJacobi.cpp Matrix08.cpp Vector08.cpp  Matrix08.h Vector08.h
	g++ -Wall RunJacobi.cpp Matrix08.cpp  Vector08.cpp -o RunJacobi -lm
